name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: python -m pip install poetry

    - name: Build and publish
      env:
        # TODO: Set PYPI_USERNAME and PYPI_PASSWORD in Settings > Secrets
        POETRY_USERNAME: ${{ secrets.PYPI_USERNAME }}
        POETRY_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry build
        poetry publish -u $POETRY_USERNAME -p $POETRY_PASSWORD
